# Generated by Django 4.0.5 on 2023-11-25 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0002_rename_owner_name_contact_owner_phone_other_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='home_type',
            field=models.TextField(blank=True, null=True),
        ),
    ]
