# Generated by Django 4.0.5 on 2023-12-09 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0007_alter_contact_address_alter_contact_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
