# Generated by Django 4.0.5 on 2024-01-12 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0008_alter_contact_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
