# Generated by Django 4.0.5 on 2023-11-24 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livestats', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=255)),
                ('members_count', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='JsError',
        ),
    ]
