# Generated by Django 4.0.5 on 2023-11-24 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livestats', '0002_roomstats_delete_jserror'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomstats',
            name='timestamp',
        ),
    ]
