# Generated by Django 4.0.5 on 2023-11-24 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livestats', '0003_remove_roomstats_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebSocketConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_group', models.CharField(max_length=255)),
                ('connection_time', models.DateTimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='RoomStats',
        ),
    ]
