# Generated by Django 4.0.5 on 2023-11-24 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livestats', '0004_websocketconnection_delete_roomstats'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WebSocketConnection',
        ),
    ]
