# Generated by Django 4.0.5 on 2024-03-12 22:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist_name', models.CharField(max_length=255)),
                ('track_title', models.CharField(max_length=255)),
                ('track_number', models.IntegerField()),
                ('album_name', models.CharField(max_length=255)),
                ('release_date', models.DateField()),
                ('isrc', models.CharField(blank=True, max_length=20, null=True)),
                ('album_art', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DownloadedSong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('download_date', models.DateTimeField(auto_now_add=True)),
                ('file_path', models.FileField(upload_to='downloaded_songs/')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spotify.song')),
            ],
        ),
    ]
