# Generated by Django 4.0.5 on 2024-01-20 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xppda', '0062_alter_gpscheckin_id_alter_monitorfeedback_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='api_key',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
