# Generated by Django 2.2.16 on 2022-10-27 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='path',
            field=models.CharField(blank=True, max_length=5128, null=True),
        ),
    ]
