# Generated by Django 4.0.5 on 2022-09-03 00:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KeyPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField()),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=64)),
                ('username', models.CharField(blank=True, max_length=4096, null=True)),
                ('password', models.CharField(blank=True, max_length=4096, null=True)),
                ('name', models.CharField(blank=True, max_length=4096, null=True)),
                ('error', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('alive', models.BooleanField(default=False)),
                ('in_use', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SystemSpecs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('architecture', models.CharField(max_length=100)),
                ('cpu_op_modes', models.CharField(max_length=100)),
                ('byte_order', models.CharField(max_length=100)),
                ('cpu_s', models.IntegerField()),
                ('on_line_cpu_s_list', models.CharField(max_length=100)),
                ('threads_per_core', models.CharField(max_length=100)),
                ('cores_per_socket', models.CharField(max_length=100)),
                ('sockets', models.CharField(max_length=100)),
                ('numa_nodes', models.CharField(max_length=100)),
                ('vendor_id', models.CharField(max_length=100)),
                ('cpu_family', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('model_name', models.CharField(max_length=100)),
                ('stepping', models.CharField(max_length=100)),
                ('cpu_mhz', models.CharField(max_length=100)),
                ('bogo_mips', models.CharField(max_length=100)),
                ('hypervisor_vendor', models.CharField(max_length=100)),
                ('virtualization_type', models.CharField(blank=True, max_length=100, null=True)),
                ('l1d_cache', models.CharField(max_length=100)),
                ('l1i_cache', models.CharField(max_length=100)),
                ('l2_cache', models.CharField(max_length=100)),
                ('l3_cache', models.CharField(max_length=100)),
                ('total_memory', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, max_length=64, null=True)),
                ('command', models.CharField(blank=True, max_length=4096, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('repo', models.CharField(blank=True, max_length=4096, null=True)),
                ('name', models.CharField(blank=True, max_length=4096, null=True)),
                ('meta', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('environment_variable', models.JSONField(blank=True, default=dict, null=True)),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TaskLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stdout', models.TextField(blank=True, null=True)),
                ('file_log', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.task')),
            ],
        ),
        migrations.CreateModel(
            name='ServerUserKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keypair', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.keypair')),
                ('server', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.server')),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='server',
            name='system_specs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.systemspecs'),
        ),
        migrations.AddField(
            model_name='server',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='TaskServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.server')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.task')),
            ],
            options={
                'unique_together': {('task', 'server')},
            },
        ),
    ]
