# Generated by Django 4.0.5 on 2022-06-17 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemspecs',
            name='cpu_s',
            field=models.IntegerField(),
        ),
    ]
