# Generated by Django 2.2.20 on 2022-05-30 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_githubhook_pipeline'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='stderr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='stdout',
            field=models.TextField(null=True),
        ),
    ]
