# Generated by Django 4.0.5 on 2022-06-17 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_systemspecs_cpu_s'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemspecs',
            name='total_memory',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
