# Generated by Django 4.0.5 on 2022-06-20 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_systemspecs_total_memory'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipeline',
            name='status',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
