# Generated by Django 4.0.5 on 2022-09-20 12:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0003_remove_servergroup_servers_servergroup_servers'),
    ]

    operations = [
        migrations.AddField(
            model_name='servergroup',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
