# Generated by Django 3.1.4 on 2022-07-02 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_task_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='meta',
            field=models.TextField(blank=True, null=True),
        ),
    ]
