# Generated by Django 2.2.20 on 2022-06-08 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_auto_20220608_2222'),
    ]

    operations = [
        migrations.RenameField(
            model_name='systemspecs',
            old_name='authentic_amd',
            new_name='vendor_id',
        ),
    ]
