# Generated by Django 2.2.20 on 2022-06-08 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_auto_20220608_2235'),
    ]

    operations = [
        migrations.RenameField(
            model_name='systemspecs',
            old_name='address_sizes',
            new_name='hypervisor_vendor',
        ),
        migrations.RenameField(
            model_name='systemspecs',
            old_name='cpu_max_mhz',
            new_name='numa_nodes',
        ),
        migrations.RenameField(
            model_name='systemspecs',
            old_name='cpu_min_mhz',
            new_name='virtualization_type',
        ),
        migrations.RemoveField(
            model_name='systemspecs',
            name='frequesncy_boost',
        ),
        migrations.RemoveField(
            model_name='systemspecs',
            name='numa_codes',
        ),
        migrations.RemoveField(
            model_name='systemspecs',
            name='virtualization',
        ),
    ]
