# Generated by Django 4.0.5 on 2023-01-31 21:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0009_command_projectmember_projectservice_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Command',
            new_name='ProjectCommand',
        ),
        migrations.RemoveField(
            model_name='projectservice',
            name='start_command',
        ),
        migrations.AddField(
            model_name='projectservice',
            name='command',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.projectcommand'),
        ),
    ]
