# Generated by Django 2.2.20 on 2022-06-08 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_server_alive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemspecs',
            name='virtualization_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
