# Generated by Django 3.1.4 on 2022-06-09 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_auto_20220608_2327'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemspecs',
            name='total_memory',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
