# Generated by Django 4.0.5 on 2022-08-03 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_githubhook_user_pipeline_user_server_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serveruserkey',
            name='keypair',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.keypair'),
        ),
        migrations.AlterField(
            model_name='serveruserkey',
            name='server',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.server'),
        ),
    ]
