# Generated by Django 4.0.5 on 2022-09-02 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_alter_serveruserkey_keypair_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GithubHook',
        ),
    ]
