# Generated by Django 3.1.4 on 2022-06-09 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_systemspecs_total_memory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemspecs',
            name='total_memory',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
