# Generated by Django 4.0.5 on 2023-01-31 23:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_projectservice_server_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectServiceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stdout', models.TextField(blank=True, null=True)),
                ('file_log', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='tasklog',
            name='task',
        ),
        migrations.AlterUniqueTogether(
            name='taskserver',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='taskserver',
            name='server',
        ),
        migrations.RemoveField(
            model_name='taskserver',
            name='task',
        ),
        migrations.RemoveField(
            model_name='projectcommand',
            name='repo',
        ),
        migrations.AddField(
            model_name='projectcommand',
            name='status',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='projectservice',
            name='status',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.DeleteModel(
            name='Task',
        ),
        migrations.DeleteModel(
            name='TaskLog',
        ),
        migrations.DeleteModel(
            name='TaskServer',
        ),
        migrations.AddField(
            model_name='projectservicelog',
            name='project_service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.projectservice'),
        ),
    ]
