# Generated by Django 4.0.5 on 2022-06-13 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0012_auto_20220609_1008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='githubhook',
            name='repo',
        ),
        migrations.RemoveField(
            model_name='task',
            name='stderr',
        ),
        migrations.RemoveField(
            model_name='task',
            name='stdout',
        ),
        migrations.CreateModel(
            name='TaskLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stdout', models.TextField(blank=True, null=True)),
                ('file_log', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.task')),
            ],
        ),
    ]
