# Generated by Django 4.0.5 on 2022-06-13 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0013_remove_githubhook_repo_remove_task_stderr_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PipelineServer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pipeline', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.pipeline')),
                ('server', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.server')),
            ],
        ),
    ]
