# Generated by Django 4.0.5 on 2022-06-13 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0014_pipelineserver'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pipelineserver',
            unique_together={('pipeline', 'server')},
        ),
    ]
