# Generated by Django 4.0.5 on 2023-09-21 23:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0014_projectservice_user_project_org'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmember',
            name='added_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='added_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectmember',
            name='admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projectmember',
            name='org',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.org'),
        ),
    ]
