# Generated by Django 4.0.5 on 2023-09-25 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0016_remove_projectservice_command_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectcommand',
            old_name='last_finished_at',
            new_name='finished_at',
        ),
        migrations.RenameField(
            model_name='projectcommand',
            old_name='last_started_at',
            new_name='started_at',
        ),
    ]
