# Generated by Django 2.2.20 on 2022-06-14 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0017_auto_20220614_2103'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='in_use',
            field=models.BooleanField(default=False),
        ),
    ]
