# Generated by Django 4.0.5 on 2023-09-26 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0016_projectcommandlog'),
        ('tasks', '0017_rename_last_finished_at_projectcommand_finished_at_and_more'),
    ]

    operations = [
    ]
