# Generated by Django 2.2.20 on 2022-06-15 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0018_server_in_use'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='repo',
            field=models.CharField(blank=True, max_length=4096, null=True),
        ),
    ]
