# Generated by Django 3.2.10 on 2023-10-10 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0018_merge_20230926_0629'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatsEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system', models.CharField(max_length=100)),
                ('node_name', models.CharField(max_length=100)),
                ('release', models.CharField(max_length=100)),
                ('version', models.CharField(max_length=255)),
                ('machine', models.CharField(max_length=100)),
                ('processor', models.CharField(max_length=100)),
                ('ip_address', models.GenericIPAddressField()),
                ('mac_address', models.CharField(max_length=100)),
                ('total_swap', models.CharField(max_length=100)),
                ('swap_free', models.CharField(max_length=100)),
                ('used_swap', models.CharField(max_length=100)),
                ('swap_percentage', models.FloatField()),
                ('total_bytes_sent', models.CharField(max_length=100)),
                ('total_bytes_received', models.CharField(max_length=100)),
                ('total_read', models.CharField(max_length=100)),
                ('total_write', models.CharField(max_length=100)),
            ],
        ),
    ]
