# Generated by Django 4.0.5 on 2022-06-15 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0019_syestemspecss_alter_server_system_specs_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSpecs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('architecture', models.CharField(max_length=100)),
                ('cpu_op_modes', models.CharField(max_length=100)),
                ('byte_order', models.CharField(max_length=100)),
                ('cpu_s', models.CharField(max_length=100)),
                ('on_line_cpu_s_list', models.CharField(max_length=100)),
                ('threads_per_core', models.CharField(max_length=100)),
                ('cores_per_socket', models.CharField(max_length=100)),
                ('sockets', models.CharField(max_length=100)),
                ('numa_nodes', models.CharField(max_length=100)),
                ('vendor_id', models.CharField(max_length=100)),
                ('cpu_family', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('model_name', models.CharField(max_length=100)),
                ('stepping', models.CharField(max_length=100)),
                ('cpu_mhz', models.CharField(max_length=100)),
                ('bogo_mips', models.CharField(max_length=100)),
                ('hypervisor_vendor', models.CharField(max_length=100)),
                ('virtualization_type', models.CharField(blank=True, max_length=100, null=True)),
                ('l1d_cache', models.CharField(max_length=100)),
                ('l1i_cache', models.CharField(max_length=100)),
                ('l2_cache', models.CharField(max_length=100)),
                ('l3_cache', models.CharField(max_length=100)),
                ('total_memory', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='server',
            name='system_specs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.systemspecs'),
        ),
        migrations.DeleteModel(
            name='SyestemSpecss',
        ),
    ]
