# Generated by Django 4.0.5 on 2023-11-13 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0020_apikey'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=4096, null=True)),
                ('error', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_active_at', models.DateTimeField(auto_now_add=True)),
                ('alive', models.BooleanField(default=False)),
                ('api_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.apikey')),
                ('system_specs', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.systemspecs')),
            ],
        ),
    ]
