# Generated by Django 3.2.23 on 2023-11-15 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0022_auto_20231115_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='alive',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='agent',
            name='api_key',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tasks.apikey'),
        ),
        migrations.AlterField(
            model_name='apikey',
            name='key',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
