# Generated by Django 3.2.23 on 2023-11-15 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0023_auto_20231115_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='api_key',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tasks.apikey'),
        ),
    ]
