# Generated by Django 4.0.5 on 2023-12-05 01:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0025_audiochunk'),
    ]

    operations = [
        migrations.AddField(
            model_name='statsentry',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.agent'),
        ),
    ]
