# Generated by Django 4.0.5 on 2023-12-05 03:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=512, unique=True)),
                ('password', models.CharField(max_length=512)),
                ('active_on_server', models.BooleanField(default=False)),
                ('hash_password', models.CharField(blank=True, max_length=512, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(blank=True, max_length=512)),
                ('mail_from', models.EmailField(max_length=254)),
                ('mail_to', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=512)),
                ('message', models.TextField()),
                ('local_date', models.CharField(max_length=128)),
                ('row_date', models.CharField(max_length=128)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailapi.account')),
            ],
        ),
    ]
