# Generated by Django 4.0.5 on 2023-12-07 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mail',
            name='body',
            field=models.TextField(blank=True, null=True),
        ),
    ]
