# Generated by Django 4.0.5 on 2023-12-07 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailapi', '0003_mail_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='mail',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
