# Generated by Django 4.0.5 on 2023-12-29 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailapi', '0004_mail_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='mail',
            name='draft',
            field=models.BooleanField(default=False),
        ),
    ]
