# Generated by Django 4.0.5 on 2023-12-07 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatapirequest',
            name='asked_amount',
            field=models.IntegerField(default=0),
        ),
    ]
