# Generated by Django 4.0.5 on 2024-01-04 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0002_chatapirequest_asked_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAW',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_content', models.TextField()),
                ('response_content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
