# Generated by Django 4.0.5 on 2023-11-29 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0003_view'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='file_type',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AddField(
            model_name='upload',
            name='filename',
            field=models.CharField(default=None, max_length=4000),
        ),
    ]
