# Generated by Django 4.0.5 on 2023-11-29 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0004_upload_file_type_upload_filename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='file_type',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='upload',
            name='filename',
            field=models.CharField(default='', max_length=4000),
        ),
    ]
