# Generated by Django 4.0.5 on 2023-12-04 18:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('storage', '0005_alter_upload_file_type_alter_upload_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='view',
            name='ended_at',
            field=models.DateTimeField(blank=True, default=None),
        ),
        migrations.AddField(
            model_name='view',
            name='upload',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='storage.upload'),
        ),
        migrations.AddField(
            model_name='view',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
