# Generated by Django 4.0.5 on 2023-12-04 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0006_view_ended_at_view_upload_view_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='view',
            name='ended_at',
        ),
    ]
