# Generated by Django 4.0.5 on 2023-12-04 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0007_remove_view_ended_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='view',
            name='exit_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
