# Generated by Django 4.0.5 on 2024-04-02 22:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ashe', '0009_upload_url_upload_file_type_upload_filename_and_more'),
        ('storage', '0009_youtubevideo_profileinfo_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='upload',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='ashe.upload'),
        ),
        migrations.AlterField(
            model_name='view',
            name='upload',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='ashe.upload'),
        ),
        migrations.DeleteModel(
            name='Upload',
        ),
    ]
