# Generated by Django 4.0.5 on 2024-05-10 01:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0010_alter_comment_upload_alter_view_upload_delete_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtubevideo',
            name='mediA',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='storage.media'),
        ),
    ]
