# Generated by Django 4.0.5 on 2024-05-20 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0011_youtubevideo_media'),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('description', models.TextField()),
                ('subscribers', models.IntegerField()),
                ('videos', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='youtubevideo',
            name='channel',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='storage.channel'),
        ),
    ]
