# Generated by Django 4.0.5 on 2024-05-20 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0013_channel_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='channel',
            name='subscribers',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='channel',
            name='videos',
            field=models.IntegerField(default=0),
        ),
    ]
