# Generated by Django 4.0.5 on 2024-05-30 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0014_alter_channel_description_alter_channel_subscribers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='soundfile',
            field=models.BooleanField(default=False),
        ),
    ]
