# Generated by Django 4.0.5 on 2024-06-23 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0015_alter_channel_name'),
        ('storage', '0015_media_soundfile'),
    ]

    operations = [
    ]
