# Generated by Django 2.1.4 on 2018-12-27 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dappx', '0003_auto_20181227_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='phone',
            field=models.CharField(blank=True, max_length=17),
        ),
    ]
