# Generated by Django 2.1.4 on 2019-01-05 23:36

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dappx', '0008_gspcheckin'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GspCheckin',
            new_name='GpsCheckin',
        ),
    ]
