# Generated by Django 2.1.4 on 2019-01-05 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dappx', '0009_auto_20190105_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gpscheckin',
            name='lat',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='gpscheckin',
            name='lng',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='gpscheckin',
            name='msg',
            field=models.CharField(default='', max_length=2000),
        ),
    ]
