# Generated by Django 2.1.4 on 2019-01-06 00:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dappx', '0010_auto_20190105_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gpscheckin',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
