# Generated by Django 2.1.4 on 2019-01-28 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dappx', '0011_auto_20190106_0011'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='notify_email',
            field=models.CharField(blank=True, max_length=512),
        ),
    ]
