# Generated by Django 2.1.5 on 2019-02-11 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dappx', '0012_userprofileinfo_notify_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='days_sober',
            field=models.IntegerField(default=0),
        ),
    ]
