# Generated by Django 2.1.5 on 2019-02-12 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dappx', '0013_userprofileinfo_days_sober'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='days_sober',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
