# Generated by Django 2.2 on 2019-06-26 11:35

from django.db import migrations, models
import hashlib


def set_user_hashes(apps, schema_editor):
    ProfileInfo = apps.get_model("dappx", "UserProfileInfo")
    for profile in ProfileInfo.objects.all():
        user_hash = hashlib.sha1(profile.user.email.encode('utf-8'))
        profile.user_hash = user_hash.hexdigest()
        profile.save()


class Migration(migrations.Migration):

    dependencies = [
        ('dappx', '0015_auto_20190622_0924'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='user_hash',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.RunPython(set_user_hashes),
    ]
