# Generated by Django 2.2 on 2019-07-12 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dappx', '0017_userprofileinfo_is_monitor_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='is_monitor_user',
        ),
    ]
