# Generated by Django 2.2.3 on 2019-07-19 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dappx', '0018_remove_userprofileinfo_is_monitor_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoupload',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
