# Generated by Django 2.2.3 on 2019-08-09 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dappx', '0021_usermonitor'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoupload',
            name='source',
            field=models.CharField(default='', max_length=500),
        ),
    ]
