# Generated by Django 2.2.5 on 2019-09-25 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dappx', '0025_auto_20190814_2215'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
