# Generated by Django 2.2.9 on 2020-01-11 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dappx', '0026_userprofileinfo_stripe_subscription_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='sober_date',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
