# Generated by Django 2.2.12 on 2020-06-09 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dappx', '0027_userprofileinfo_sober_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='gpscheckin',
            name='monitor_feedback',
            field=models.ManyToManyField(to='dappx.MonitorFeedback'),
        ),
    ]
