# Generated by Django 3.0.2 on 2021-02-01 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dappx', '0029_auto_20210201_0617'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofileinfo',
            old_name='iap_apple_blurb',
            new_name='iap_blurb',
        ),
    ]
