# Generated by Django 2.2.13 on 2021-04-19 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dappx', '0030_auto_20210201_0622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='days_sober',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='name',
            field=models.CharField(blank=True, max_length=17, null=True),
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='phone',
            field=models.CharField(blank=True, max_length=17, null=True),
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='source',
            field=models.CharField(default='', max_length=500, null=True),
        ),
    ]
