# Generated by Django 2.2.13 on 2021-06-22 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dappx', '0031_subscriptionevent'),
        ('dappx', '0031_auto_20210419_1007'),
    ]

    operations = [
    ]
