# Generated by Django 2.2.13 on 2021-06-22 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dappx', '0033_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='org',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='dappx.Organization'),
        ),
    ]
