# Generated by Django 2.2.13 on 2021-06-22 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dappx', '0035_auto_20210622_2012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='org',
        ),
    ]
