# Generated by Django 2.2.13 on 2021-06-22 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dappx', '0036_remove_userprofileinfo_org'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Organization',
        ),
    ]
