# Generated by Django 2.2.13 on 2021-06-22 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dappx', '0040_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='user_org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dappx.Organization'),
        ),
    ]
