# Generated by Django 2.2.13 on 2021-06-22 21:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dappx', '0042_organizationmember'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationmember',
            name='admin',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.CreateModel(
            name='OrganizationMemberMonitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
