# Generated by Django 2.2.16 on 2021-07-13 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dappx', '0043_auto_20210622_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationmember',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dappx.Organization'),
        ),
    ]
