# Generated by Django 2.2.16 on 2021-07-15 04:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dappx', '0044_organizationmember_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationmember',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='member_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
