# Generated by Django 2.2.16 on 2021-07-15 05:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dappx', '0046_auto_20210715_0452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gpscheckin',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
