# Generated by Django 2.2.13 on 2021-07-20 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dappx', '0048_usermonitor_organization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermonitor',
            name='organization',
        ),
    ]
