# Generated by Django 2.2.13 on 2021-07-20 22:26

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dappx', '0050_organizationmembermonitor_client'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='organizationmember',
            unique_together={('user',)},
        ),
    ]
