# Generated by Django 2.2.13 on 2021-09-20 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dappx', '0051_auto_20210720_2226'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='login_code',
            field=models.CharField(blank=True, max_length=17, null=True),
        ),
    ]
