# Generated by Django 2.2.16 on 2021-09-21 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dappx', '0052_userprofileinfo_login_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='hostname',
            field=models.CharField(default='', max_length=500),
        ),
    ]
