# Generated by Django 2.2.16 on 2021-09-21 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dappx', '0053_organization_hostname'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='phone_num',
            field=models.CharField(blank=True, max_length=17, null=True),
        ),
    ]
