# Generated by Django 2.2.16 on 2021-09-21 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dappx', '0054_userprofileinfo_phone_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='notify_all',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
