# Generated by Django 2.2.16 on 2022-05-02 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dappx', '0055_organization_notify_all'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=17, null=True)),
                ('name', models.CharField(blank=True, max_length=17, null=True)),
                ('website', models.CharField(blank=True, max_length=17, null=True)),
                ('email', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
