# Generated by Django 2.2.16 on 2022-05-27 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dappx', '0057_auto_20220518_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='phone_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
