# Generated by Django 4.1.4 on 2023-01-06 21:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dappx', '0060_auto_20221025_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationmembermonitor',
            name='client',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_requests_created', to=settings.AUTH_USER_MODEL),
        ),
    ]
