# Generated by Django 2.2.20 on 2022-06-08 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SystemSpecs',
        ),
    ]
