# Generated by Django 4.0.5 on 2023-11-24 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_websocket', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebSocketConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_group', models.CharField(max_length=255)),
                ('connection_time', models.DateTimeField()),
            ],
        ),
    ]
