# Generated by Django 4.0.5 on 2023-11-20 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server_websocket', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='StatsEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system', models.CharField(max_length=255)),
                ('node_name', models.CharField(max_length=255)),
                ('release', models.CharField(max_length=255)),
                ('version', models.CharField(max_length=255)),
                ('machine', models.CharField(max_length=255)),
                ('processor', models.CharField(max_length=255)),
                ('ip_address', models.CharField(max_length=255)),
                ('mac_address', models.CharField(max_length=255)),
                ('total_swap', models.CharField(max_length=255)),
                ('swap_free', models.CharField(max_length=255)),
                ('used_swap', models.CharField(max_length=255)),
                ('swap_percentage', models.FloatField()),
                ('total_bytes_sent', models.CharField(max_length=255)),
                ('total_bytes_received', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alive', models.BooleanField(default=False)),
                ('api_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server_websocket.apikey')),
            ],
        ),
    ]
