# Generated by Django 4.0.5 on 2023-11-24 12:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('server_websocket', '0003_websocketconnection_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='websocketconnection',
            name='user',
        ),
        migrations.AddField(
            model_name='websocketconnection',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='websocketconnection',
            name='username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
