# Generated by Django 4.0.5 on 2024-01-16 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ashe', '0002_device_created_at_device_last_seen'),
    ]

    operations = [
#        migrations.RenameField(
#            model_name='session',
#            old_name='ended_at',
#            new_name='ended',
#        ),
#        migrations.RenameField(
#            model_name='session',
#            old_name='started_at',
#            new_name='started',
#        ),
    ]
