# Generated by Django 4.0.5 on 2024-01-16 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ashe', '0003_rename_ended_at_session_ended_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='ended_at',
        ),
        migrations.RemoveField(
            model_name='session',
            name='started_at',
        ),
    ]
