# Generated by Django 4.0.5 on 2024-01-16 05:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ashe', '0004_remove_session_ended_at_remove_session_started_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='ended',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='started',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
