# Generated by Django 4.0.5 on 2024-01-16 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ashe', '0005_session_ended_session_started'),
    ]

    operations = [
#        migrations.RenameField(
#            model_name='session',
#            old_name='started',
#            new_name='start',
#        ),
    ]
