# Generated by Django 4.0.5 on 2024-03-25 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ashe', '0006_rename_started_session_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='token',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ashe.token'),
        ),
    ]
