# Generated by Django 4.0.5 on 2024-03-27 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ashe', '0007_session_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ashe.device'),
        ),
    ]
