# Generated by Django 4.0.5 on 2024-04-02 22:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ashe', '0008_upload_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='Url',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='upload',
            name='file_type',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='upload',
            name='filename',
            field=models.CharField(default='', max_length=4000),
        ),
        migrations.AddField(
            model_name='upload',
            name='path',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='upload',
            name='source',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='upload',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
