# Generated by Django 4.0.5 on 2024-05-01 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ashe', '0009_upload_url_upload_file_type_upload_filename_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='token',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
